### ISSUE TITLE
Erweitern des Interfaces um "letzte_verfügbare_position"

### ISSUE THREAD

**Issue by jrebstadt** [JarnoRFB/bussistant#7]
Erweitern des Interfaces um "letzte_verfügbare_position" für gegebenen FahrtenBezeichner

**Comment by TinoM** [comment]
Endpunkt vorhanden:
https://swms-conterra.fmecloud.com/fmedatastreaming/IVU/service.fmw/busse 

bzw.
https://swms-conterra.fmecloud.com/fmedatastreaming/IVU/service.fmw/busse?fahrtbezeichner=-1234567
